### ISSUE TITLE
React Implementation Request

### ISSUE THREAD

**Issue by nosh247** [openforge/ionic-phaser-game-template#22]
- Loved the webinar, but would it be possible to have a react implementation for this.

**Comment by Master244** [comment]
dig a little bit into NX you can generate a new app and build your React frontend there. You can reuse the data-acces-model stuff so you only need to write your own wrapper for phaser, which is well described out there:

https://tnodes.medium.com/integrating-react-and-phaser-3-tutorial-eb96717d4a9d

:) happy coding! make a PR here if you can!

**Comment by Ricardo385** [comment]
Hey @nosh247 ! We are so sorry for the late response but thank you for using our template! We recently updated our repo and docs in order to use the latest technologies versions and we integrate React! You can take a look to our README and follow the instructions. I'm going to close this issue since has been solved. Regards
